drop table heaterconfigkeyvalue if EXISTS;
drop table Period if EXISTS;

create table heaterconfigkeyvalue (
	thekey varchar(50) not null,
	value varchar(50) not null,
	lastmodified date not null,
	constraint pk_heaterconfigkeyvalue primary key(thekey)
	);

create table Period (
 	id int GENERATED BY DEFAULT AS IDENTITY,
 	start_Date date  not null,
 	effective_Start date,
 	stop_Date date not null,
 	effective_Stop date,
 	comment varchar(80) not null,
 	constraint pk_Period primary key(id)
 	);
